### ISSUE TITLE
Fix date test fails 

### ISSUE THREAD

**Issue by nikcorg** [toddself/node-parsely#8]
In my timezone (CET+2) the `fix-date` test fails, because the `toISOString` method reduces the time difference to GMT from the parsed date, essentially changing the resolved day to the one before.

    > new Date('May 1, 2001')
    Tue May 01 2001 00:00:00 GMT+0300 (EEST)
    > new Date('May 1, 2001').toISOString()
    '2001-04-30T21:00:00.000Z'

**Comment by toddself** [comment]
Thanks!  I changed the date formatting.

**Comment by toddself** [comment]
Version 1.0.3 is now published to NPM.

Thanks for the help on this!

**Comment by nikcorg** [comment]
You're most welcome. Thanks for the quick fixes :-)
